defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 49a80872-a204-456a-9de2-9c432c1cf23e # Community
handle: community
maxAuthors: 1
minAuthors: 1
name: Community
propagationMethod: all
siteSettings:
  6f1c52ab-18f0-43de-953c-d0beb8e1fbf8: # Val-Dieu
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
