defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 81bb436b-a731-48ff-8771-aba37f45bcb5 # Homepage
handle: homepage
maxAuthors: 1
minAuthors: 1
name: Homepage
propagationMethod: all
siteSettings:
  6f1c52ab-18f0-43de-953c-d0beb8e1fbf8: # Val-Dieu
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
