columnSuffix: null
handle: communityAgendaMonday
instructions: 'Créneaux horaires pour Agenda - Lundi.'
name: 'Agenda - Lundi'
searchable: true
settings:
  addRowLabel: 'Ajouter un créneau'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Horaire
            -
              - handle
              - time
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Texte
            -
              - handle
              - title
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - time
          - 8h
        -
          - title
          - Laudes
    -
      __assoc__:
        -
          - time
          - 18h-18h40
        -
          - title
          - 'Vêpres + Eucharistie'
    -
      __assoc__:
        -
          - time
          - 18h40-19h15
        -
          - title
          - 'Lectio Divina'
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
