allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c69da2c2-921e-4cb3-932a-770b442d3f61:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Internal title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 69d36bcb-4919-4bbd-9088-e2c7fc844709
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 068ee5b9-ade5-4e9e-8de6-d175dc708285 # Discover timeline
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaa43660-9b09-4cbb-83b0-f74050b54322
            userCondition: null
            warning: null
            width: 100
        name: Timeline
        uid: 20a0b909-6377-4ec6-9bdd-aa70ddab14a0
        userCondition: null
    thumbFieldKey: null
handle: discover
hasTitleField: true
icon: null
name: Discover
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
