allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  fc9d0572-dce1-40e0-8626-9adf3f55ccc9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Internal title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 71d309f0-0434-4d9e-8d58-e576850e9ef9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c3e72f09-60d8-41ec-8c47-764a10460434 # Homepage gallery
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67ccda28-c8a0-48f1-98eb-262fe0373a01
            userCondition: null
            warning: null
            width: 100
        name: Galerie
        uid: fd779973-9c7a-481d-8fab-dedf778b1073
        userCondition: null
    thumbFieldKey: null
handle: homepage
hasTitleField: true
icon: null
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
