allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8aca31c9-d8af-48c5-be2e-f5a26215070d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Internal title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 3b50c32d-b083-441f-ae46-035e07bbfebb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0b557883-5ba9-4d6e-b5bc-21a347def43a # Support projects
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 608c8d6f-efb1-4f53-8686-b44aabe8a62d
            userCondition: null
            warning: null
            width: 100
        name: Projets
        uid: 2cdf00a7-2d86-4478-b76a-ec65bb9863d9
        userCondition: null
    thumbFieldKey: null
handle: support
hasTitleField: true
icon: null
name: Support
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
